### ISSUE TITLE
Multi-Camera Capture (enhancement)

### ISSUE THREAD

**Issue by Jokonut** [yasuohasegawa/UnityiOSNativeCameraTest#1]
Hello Yasuo!
You did a great job in implementing this native iOs Camera to unity, but did you manage to do the same thing for multiple cameras ?
I found nothing on the subject except the official documentation.
https://developer.apple.com/videos/play/wwdc2019/249/

If you have some time, can you help me implement this ?

Thank you.

**Comment by yasuohasegawa** [comment]
Hi Jokonut!
Thank you so much for your comment! I have not heard about the multiple-camera things. That's exciting stuff.
Let me try to implement it if I have time. First, I need to check the swift implementation of the multi-camera.
I'll let you know when I have done it.

Best,

**Comment by yasuohasegawa** [comment]
Hi Jokonut,

I implemented the Multi-Cam capture feature for iOS and pushed my changes into the Main branch.
Before you build, you need to set up the following things.

・In the iOS player setting, you need to set up the os minimum version to 13.0 and default orientation to the Portrait.
The Multi-Cam capture requires the iOS version above 13.0.

・In the build setting, you need to add the MultiCam scene only.

We did not optimize and refactor my code. It's just a simple sample code to ensure the feature works out. If you want to use this code in your production, you might need to take care of the memory and performance. Also, it needs to test the different models of iOS devices.

We only tested this sample on iPhone 12 pro with OS 16. It works great for me. It will capture both the front and back cameras at the same time.

I hope this will help you.

Best,

**Comment by Jokonut** [comment]
Ho boy you did it ! 
Thank you so much... This feature have so much potential :)
